### ISSUE TITLE
Failing to build on Windows

### ISSUE THREAD

**Issue by KSXGitHub** [allenap/shell-quote#1]
Windows do have BASH Shell. So I think this crate could be useful there. I also want to use this crate in my cross-platform application.

**Comment by allenap** [comment]
Hi @KSXGitHub, can you share the build errors from Windows?

**Comment by KSXGitHub** [comment]
@allenap It was caused by this line: https://github.com/allenap/shell-quote/blob/5624564590927c1d1f7d34f02cb9cb50d551f2d5/src/sh.rs#L49

Windows doesn't have `std::os::unix`.

**Comment by allenap** [comment]
Hi @KSXGitHub, the [0.5.0 release](https://crates.io/crates/shell-quote/0.5.0) avoids importing `std::os::unix` so this ought to compile on Windows now. The API has changed a lot, but there are examples in the docs.

Of course, I may have made a mistake – I haven't configured CI for Windows yet, and I don't have a Windows machine with tooling on it to test – so if you're still interested in this package, please let me know if you hit issues. For the moment I'm able to respond more quickly than before.

**Comment by KSXGitHub** [comment]
@allenap I have already forgot why I wanted to use this crate, so you cannot expect me to test your new release now.
